### ISSUE TITLE
Cython with Python 3.7

### ISSUE THREAD

**Issue by emmatyping** [smira/py-numa#8]
It appears that a newer Cython is needed to support Python3.7. I have Cython installed, but it seems not to generate new C sources. Perhaps a new package could be uploaded that has regenerated sources based on the latest Cython? Or will generate new sources correctly? Greatly appreciated and thank you for working on this project!

**Comment by smira** [comment]
I see no problem in Travis with 3.7 (#9), if you have any specific problem or a fix, please feel free to submit a PR for it.
